#配置项目名
server:
  servlet:
    context-path: /jxc


#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jxc_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  #配置视图解析器
  mvc:
    view:
      prefix: /WEB-INF/backend/
      suffix: .jsp
    #设置springmvc接受的时间格式
    date-format: yyyy-MM-dd
  #设置springmvc输出的时间格式
  jackson:
    date-format: yyyy-MM-dd
    #查到的时间标准是伦敦时间，北京时间多8个小时
    time-zone: GMT+8


#配置实体的包名
mybatis:
  type-aliases-package: com.aaa.entity

  pagehelper:
        helperDialect: mysql
        reasonable: true
        supportMethodsArguments: true
        params: count=countSql
        returnPageInfo: check
